In [ ]:
####################
#
# Alexandra Kozachok
#
####################
# this file contains implementation of Hamming distance via Inner Product
# couple of different realisations are tested :
#  - using Python standart types, functions and libraries
#  - using NumPy
####################

In [1]:
###################################################################################################
###################################################################################################
###################################################################################################

In [2]:
import random

class Alexa_Hamming:
    #using standart Python integer type

    @staticmethod
    def get_random_vector_of_minusOneAndOnes(xSize = 16):
        return [random.randrange(-1, 2, 2) for xIndex in range(xSize)]
    
    @staticmethod
    def set_of_types(*args):
        xSet_of_types = set([])
        for arg in args:
            xSet_of_types.add(type(arg))
        return xSet_of_types
    
    @staticmethod
    def is_iterable_object(arg):
        try:
            iterator = iter(arg)
            #print(arg, 'is iterable')
            return True
        except TypeError as iterator_error:
            #print(arg, 'is not iterable')
            return False
        
    @staticmethod
    def is_iterable(*args):
        for arg in args:
            if Alexa_Hamming.is_iterable_object(arg):
                pass
            else:
                return False
        return True
        
    @staticmethod
    def is_size_the_same(*args):
        xSet_of_sizes = set([])
        for arg in args:
            xSet_of_sizes.add(len(arg))
        if 1 == len(xSet_of_sizes):
            return True
        else:
            return False

    @staticmethod
    def signed_inner_product(xVec1, xVec2):
        xSigned_inner_product = 0
        for i in range(len(xVec1)):
            xSigned_inner_product += (xVec1[i]*xVec2[i])
        return xSigned_inner_product
    
    @staticmethod
    def unsigned_inner_product(xVec1, xVec2):
        return abs(Alexa_Hamming.signed_inner_product(xVec1, xVec2))
    
    @staticmethod
    def different_bits_via_signed_inner_product(xVec1, xVec2):
        return ((len(xVec1) - Alexa_Hamming.signed_inner_product(xVec1, xVec2)) // 2)
    
    @staticmethod
    def hamming_distance(xVec1, xVec2, xType = list):
        assert Alexa_Hamming.is_iterable(xVec1, xVec2), \
        "at least one of arg is not iterable object (could not be a vector)"
        assert set([xType]) == Alexa_Hamming.set_of_types(xVec1, xVec2), \
        "objects are of different types or function needs other types of vectors"
        assert Alexa_Hamming.is_size_the_same(xVec1, xVec2), \
        "the size (length) of args (vectors) are not the same"
        xSize = len(xVec1)
        return (Alexa_Hamming.different_bits_via_signed_inner_product(xVec1, xVec2)/xSize)

    @staticmethod
    def hamming_distance_typeList_fast(xVec1, xVec2, xSize = 16):
        return ((xSize - sum([xVec1[i]*xVec2[i] for i in range(xSize)])) / (2*xSize))
    
    @staticmethod
    def hamming_distance_typeList_length16_fast(xVec1, xVec2):
        return ((16 - sum([xVec1[i]*xVec2[i] for i in range(16)])) / 32)

In [3]:
xVec1 = Alexa_Hamming.get_random_vector_of_minusOneAndOnes()
print("xVec1 = \n{0}".format(xVec1))

xVec1 = 
[1, -1, -1, 1, 1, 1, 1, -1, 1, 1, -1, 1, 1, -1, 1, 1]


In [4]:
xVec2 = Alexa_Hamming.get_random_vector_of_minusOneAndOnes(16)
print("xVec2 = \n{0}".format(xVec2))

xVec2 = 
[-1, -1, -1, -1, -1, 1, -1, 1, -1, 1, 1, 1, -1, -1, 1, -1]


In [5]:
xHamming_distance = Alexa_Hamming.hamming_distance_typeList_length16_fast(xVec1, xVec2)
print("Hamming distance between two vectors vec1 and vec2 : \n\t {0}".format(xHamming_distance))

Hamming distance between two vectors vec1 and vec2 : 
	 0.5625


In [6]:
Alexa_Hamming.hamming_distance(xVec1, xVec2)

0.5625

In [7]:
Alexa_Hamming.hamming_distance_typeList_fast(xVec1, xVec2)

0.5625

In [8]:
###################################################################################################
###################################################################################################
###################################################################################################

In [9]:
import numpy as np

class Alexa_Hamming_with_NumPy:
    
    signed_inner_product = np.inner
    
    def __init__(self, xSize = 16, xDtype=np.int8, xArrayOfPossibleValues = None):
        self.xSize = xSize
        self.xDtype = xDtype
        if xArrayOfPossibleValues is None:
            self.xArrayOfPossibleValues = np.array([-1, 1], dtype = np.int8)
        else:
            self.xArrayOfPossibleValues = xArrayOfPossibleValues
        
    def get_random_vector(self, xDistribution = None):
        # ~~None~~ stands for ~~uniform~~ distribution
        if xDistribution is None:
            return np.random.choice(self.xArrayOfPossibleValues,  self.xSize)
        else:
            assert 1.0 == np.sum(xDistribution), \
            " sum of probabilities is not one : sum(p[k]) != 1 "
            return np.random.choice(self.xArrayOfPossibleValues,  size=self.xSize, p = xDistribution)
    
    @staticmethod
    def get_random_vector_of_minusOneAndOnes_length16_elementByte1_fast():
        #uniform distribution
        return np.random.choice(np.array([-1, 1], dtype = np.int8),  size=16)
    
    @staticmethod
    def different_bits_via_signed_inner_product(arg_vec1, arg_vec2, xType = None, xSize = None, xDtype = None):
        if not xType is None:
            assert ((xType == type(arg_vec1)) and (xType == type(arg_vec2))), \
            ("arguments need to be of " + str(xType) + " !")
        if not xSize is None:
            assert ((xSize == np.size(arg_vec1, axis = 0)) and (xSize == np.size(arg_vec2, axis = 0))), \
            ("arguments need to be of " + str(xType) + " !")
        if not xSize is None:
            assert ((xDtype == arg_vec1.dtype) and (xDtype == arg_vec2.dtype)), \
            ("arguments need to be of " + str(xType) + " !")
        return \
        np.floor_divide((np.size(arg_vec1, axis = 0) - Alexa_Hamming_with_NumPy.signed_inner_product(arg_vec1, arg_vec2)), 2)
    
    @staticmethod
    def hamming_distance(arg_vec1, arg_vec2, xType = None, xSize = None, xDtype = None):
        return \
        np.divide(Alexa_Hamming_with_NumPy.different_bits_via_signed_inner_product(arg_vec1, arg_vec2, xType, xSize, xDtype), \
                  np.size(arg_vec1, axis = 0), \
                  dtype = np.float)
        #Alexa_Hamming_with_NumPy.different_bits_via_signed_inner_product(arg_vec1, arg_vec2, xType, xSize, xDtype) \
        #/np.size(arg_vec1, axis = 0)
        
    @staticmethod
    def hamming_distance_fast(arg_vec1, arg_vec2):
        return \
        np.divide(np.floor_divide((np.size(arg_vec1, axis = 0) - np.inner(arg_vec1, arg_vec2)), 2), \
                  np.size(arg_vec1, axis = 0), \
                  dtype = np.float)
    
    @staticmethod
    def hamming_distance_length16_fast(arg_vec1, arg_vec2):
        return \
        np.divide((16 - np.inner(arg_vec1, arg_vec2)), 32, dtype = np.float)

In [10]:
#using xVec1, xVec2 which have been generated above
xHamming_distance_NumPy = Alexa_Hamming_with_NumPy.hamming_distance(xVec1, xVec2)
print("""Hamming distance between two vectors
vec1 = \n{0} and 
vec2 = \n{1} : 
\n\t {2}""".format(xVec1, xVec2, xHamming_distance_NumPy))

Hamming distance between two vectors
vec1 = 
[1, -1, -1, 1, 1, 1, 1, -1, 1, 1, -1, 1, 1, -1, 1, 1] and 
vec2 = 
[-1, -1, -1, -1, -1, 1, -1, 1, -1, 1, 1, 1, -1, -1, 1, -1] : 

	 0.5625


In [11]:
xHamming_distance == xHamming_distance_NumPy

True

In [12]:
xVec1_NumPy = Alexa_Hamming_with_NumPy.get_random_vector_of_minusOneAndOnes_length16_elementByte1_fast()
print("xVec1_NumPy = \n{0}".format(xVec1_NumPy))

xVec1_NumPy = 
[-1  1  1  1 -1  1  1 -1  1  1 -1 -1 -1  1 -1  1]


In [13]:
xVec2_NumPy = Alexa_Hamming_with_NumPy.get_random_vector_of_minusOneAndOnes_length16_elementByte1_fast()
print("xVec2_NumPy = \n{0}".format(xVec2_NumPy))

xVec2_NumPy = 
[-1  1  1 -1  1  1  1  1  1 -1 -1 -1 -1  1  1  1]


In [14]:
del xHamming_distance_NumPy
xHamming_distance_NumPy = Alexa_Hamming_with_NumPy.hamming_distance(xVec1_NumPy, xVec2_NumPy)
print("Hamming distance between two vectors vec1 and vec2 : \n\t {0}".format(xHamming_distance_NumPy))

Hamming distance between two vectors vec1 and vec2 : 
	 0.3125


In [15]:
Alexa_Hamming.hamming_distance(xVec1_NumPy, xVec2_NumPy)

AssertionError: objects are of different types or function needs other types of vectors

In [16]:
Alexa_Hamming.hamming_distance(xVec1_NumPy, xVec2_NumPy, xType = np.ndarray)

0.3125

In [17]:
Alexa_Hamming.hamming_distance_typeList_fast(xVec1_NumPy, xVec2_NumPy)

0.3125

In [18]:
Alexa_Hamming.hamming_distance_typeList_length16_fast(xVec1_NumPy, xVec2_NumPy)

0.3125

In [19]:
###################################################################################################
###################################################################################################
###################################################################################################

In [ ]:

# some testing goes here


In [20]:
import datetime

In [21]:
#vectorType_NumPy = np.array
testVectorSize = 16
testVectorsNumber = 10000

In [22]:
testArray_of_random_vectors = list()
#
time_start = datetime.datetime.now()
for i in range(testVectorsNumber):
    testArray_of_random_vectors.append(Alexa_Hamming.get_random_vector_of_minusOneAndOnes())
time_end = datetime.datetime.now()
#
timedelta = (time_end - time_start)
print(""" NumPy creating testVectorsNumber = {0} of testVectorSize = {1}
using function 
~~ Alexa_Hamming.get_random_vector_of_minusOneAndOnes() ~~
\n\t timedelta = {2} """.format(testVectorsNumber, testVectorSize,\
                           timedelta.microseconds))

 NumPy creating testVectorsNumber = 10000 of testVectorSize = 16
using function 
~~ Alexa_Hamming.get_random_vector_of_minusOneAndOnes() ~~

	 timedelta = 528030 


In [23]:
testArray_of_random_vectors_NumPy = np.ndarray((testVectorsNumber, testVectorSize), dtype = np.int8)
#
time_start = datetime.datetime.now()
for i in range(testVectorsNumber):
    testArray_of_random_vectors_NumPy[i] = Alexa_Hamming_with_NumPy.get_random_vector_of_minusOneAndOnes_length16_elementByte1_fast()
time_end = datetime.datetime.now()
#
timedelta_NumPy = (time_end - time_start)
print(""" NumPy creating testVectorsNumber = {0} of testVectorSize = {1}
using function 
~~ Alexa_Hamming_with_NumPy.get_random_vector_of_minusOneAndOnes_length16_elementByte1_fast() ~~
\n\t timedelta_NumPy = {2} """.format(testVectorsNumber, testVectorSize,\
                           timedelta_NumPy.microseconds))

 NumPy creating testVectorsNumber = 10000 of testVectorSize = 16
using function 
~~ Alexa_Hamming_with_NumPy.get_random_vector_of_minusOneAndOnes_length16_elementByte1_fast() ~~

	 timedelta_NumPy = 312018 


In [24]:
print("random vector creation speed comparison (standart Python vs NumPy) : \n")
print("|timedelta - timedelta_NumPy|/timedelta       = %s" % (abs(timedelta - timedelta_NumPy)/timedelta))
print("|timedelta - timedelta_NumPy|/timedelta_NumPy = %s" % (abs(timedelta - timedelta_NumPy)/timedelta_NumPy))

random vector creation speed comparison (standart Python vs NumPy) : 

|timedelta - timedelta_NumPy|/timedelta       = 0.40909039259133007
|timedelta - timedelta_NumPy|/timedelta_NumPy = 0.6923062131030902


In [25]:
0.38740339293551895+0.6323955902921634

1.0197989832276824

In [26]:
xVecConst = [-1 for i in range(16)]
print( "xVecConst = \n %s" % xVecConst)
print( "\ttype(xVecConst) = %s" % type(xVecConst))
print( "\ttype(xVecConst[0]) = %s" % type(xVecConst[0]))

xVecConst = 
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
	type(xVecConst) = <class 'list'>
	type(xVecConst[0]) = <class 'int'>


In [27]:
time_start = datetime.datetime.now()
for i in range(testVectorsNumber):
    xV = testArray_of_random_vectors[i]
    Alexa_Hamming.hamming_distance_typeList_length16_fast(xVecConst, xV)
time_end = datetime.datetime.now()
#
timedelta = (time_end - time_start)
print(""" NumPy creating testVectorsNumber = {0} of testVectorSize = {1}
using function 
~~ Alexa_Hamming.hamming_distance_typeList_length16_fast ~~
\n\t timedelta = {2} """.format(testVectorsNumber, testVectorSize,\
                           timedelta.microseconds))

 NumPy creating testVectorsNumber = 10000 of testVectorSize = 16
using function 
~~ Alexa_Hamming.hamming_distance_typeList_length16_fast ~~

	 timedelta = 53003 


In [28]:
xVecConst_NumPy = np.array([-1 for i in range(16)], dtype = np.int8)
print( "xVecConst_NumPy = \n %s" % xVecConst_NumPy)
print( "\ttype(xVecConst_NumPy) = %s" % type(xVecConst_NumPy))
print( "\txVecConst_NumPy.dtype = %s" % xVecConst_NumPy.dtype)

xVecConst_NumPy = 
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
	type(xVecConst_NumPy) = <class 'numpy.ndarray'>
	xVecConst_NumPy.dtype = int8


In [29]:
time_start = datetime.datetime.now()
for i in range(testVectorsNumber):
    xV_NumPy = testArray_of_random_vectors_NumPy[i]
    Alexa_Hamming_with_NumPy.hamming_distance_length16_fast(xVecConst_NumPy, xV_NumPy)
time_end = datetime.datetime.now()
#
timedelta_NumPy = (time_end - time_start)
print(""" NumPy creating testVectorsNumber = {0} of testVectorSize = {1}
using function 
~~ Alexa_Hamming.hamming_distance_typeList_length16_fast ~~
\n\t timedelta_NumPy = {2} """.format(testVectorsNumber, testVectorSize,\
                           timedelta_NumPy.microseconds))

 NumPy creating testVectorsNumber = 10000 of testVectorSize = 16
using function 
~~ Alexa_Hamming.hamming_distance_typeList_length16_fast ~~

	 timedelta_NumPy = 199011 


In [30]:
import sys
print(" testArray_of_random_vectors       = %s (bytes) " % sys.getsizeof(testArray_of_random_vectors))
print(" testArray_of_random_vectors_NumPy = %s (bytes) " % sys.getsizeof(testArray_of_random_vectors_NumPy))

 testArray_of_random_vectors       = 43816 (bytes) 
 testArray_of_random_vectors_NumPy = 160056 (bytes) 


In [31]:
len(testArray_of_random_vectors) == len(testArray_of_random_vectors_NumPy)

True

In [32]:
print(" testArray_of_random_vectors[0]       = %s (bytes) " % sys.getsizeof(testArray_of_random_vectors[0]))
print(" testArray_of_random_vectors_NumPy[0] = %s (bytes) " % sys.getsizeof(testArray_of_random_vectors_NumPy[0]))

 testArray_of_random_vectors[0]       = 100 (bytes) 
 testArray_of_random_vectors_NumPy[0] = 48 (bytes) 


In [33]:
print(testArray_of_random_vectors[0])
print(testArray_of_random_vectors_NumPy[0])

[-1, -1, -1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, 1]
[ 1 -1  1 -1 -1 -1 -1 -1  1  1  1 -1 -1  1  1  1]


In [34]:
print("random vector creation speed comparison (standart Python vs NumPy) : \n")
print("|timedelta - timedelta_NumPy|/timedelta       = %s" % (abs(timedelta - timedelta_NumPy)/timedelta))
print("|timedelta - timedelta_NumPy|/timedelta_NumPy = %s" % (abs(timedelta - timedelta_NumPy)/timedelta_NumPy))

random vector creation speed comparison (standart Python vs NumPy) : 

|timedelta - timedelta_NumPy|/timedelta       = 2.7547119974341077
|timedelta - timedelta_NumPy|/timedelta_NumPy = 0.7336679882016572


In [35]:
newTestArray_of_random_vectors_NumPy = np.ndarray(testVectorsNumber, dtype = np.ndarray)
#
time_start = datetime.datetime.now()
for i in range(testVectorsNumber):
    newTestArray_of_random_vectors_NumPy[i] = Alexa_Hamming_with_NumPy.get_random_vector_of_minusOneAndOnes_length16_elementByte1_fast()
time_end = datetime.datetime.now()
#
timedelta_NumPy = (time_end - time_start)
print(""" NumPy creating testVectorsNumber = {0} of testVectorSize = {1}
using function 
~~ Alexa_Hamming_with_NumPy.get_random_vector_of_minusOneAndOnes_length16_elementByte1_fast() ~~
\n\t timedelta_NumPy = {2} """.format(testVectorsNumber, testVectorSize,\
                           timedelta_NumPy.microseconds))

 NumPy creating testVectorsNumber = 10000 of testVectorSize = 16
using function 
~~ Alexa_Hamming_with_NumPy.get_random_vector_of_minusOneAndOnes_length16_elementByte1_fast() ~~

	 timedelta_NumPy = 308017 


In [36]:
print(" testArray_of_random_vectors          = %s (bytes) " % sys.getsizeof(testArray_of_random_vectors))
print(" testArray_of_random_vectors_NumPy    = %s (bytes) " % sys.getsizeof(testArray_of_random_vectors_NumPy))
print(" newTestArray_of_random_vectors_NumPy = %s (bytes) " % sys.getsizeof(newTestArray_of_random_vectors_NumPy))

print(" testArray_of_random_vectors[0]          = %s (bytes) " % sys.getsizeof(testArray_of_random_vectors[0]))
print(" testArray_of_random_vectors_NumPy[0]    = %s (bytes) " % sys.getsizeof(testArray_of_random_vectors_NumPy[0]))
print(" newTestArray_of_random_vectors_NumPy[0] = %s (bytes) " % sys.getsizeof(newTestArray_of_random_vectors_NumPy[0]))

 testArray_of_random_vectors          = 43816 (bytes) 
 testArray_of_random_vectors_NumPy    = 160056 (bytes) 
 newTestArray_of_random_vectors_NumPy = 40048 (bytes) 
 testArray_of_random_vectors[0]          = 100 (bytes) 
 testArray_of_random_vectors_NumPy[0]    = 48 (bytes) 
 newTestArray_of_random_vectors_NumPy[0] = 64 (bytes) 


In [37]:
time_start = datetime.datetime.now()
for i in range(testVectorsNumber):
    xV_NumPy = newTestArray_of_random_vectors_NumPy[i]
    Alexa_Hamming_with_NumPy.hamming_distance_length16_fast(xVecConst_NumPy, xV_NumPy)
time_end = datetime.datetime.now()
#
newTimedelta_NumPy = (time_end - time_start)
print(""" NumPy creating testVectorsNumber = {0} of testVectorSize = {1}
using function 
~~ Alexa_Hamming.hamming_distance_typeList_length16_fast ~~
\n\t newTimedelta_NumPy = {2} """.format(testVectorsNumber, testVectorSize,\
                           newTimedelta_NumPy.microseconds))

 NumPy creating testVectorsNumber = 10000 of testVectorSize = 16
using function 
~~ Alexa_Hamming.hamming_distance_typeList_length16_fast ~~

	 newTimedelta_NumPy = 165009 


In [38]:
xVec_CONST = [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
print( sys.getsizeof( xVec_CONST ) )
print( sys.getsizeof( np.array(xVec_CONST) ) )
print( sys.getsizeof( np.array(xVec_CONST, dtype = np.byte) ) )
print( sys.getsizeof( np.array(xVec_CONST, dtype = np.int8) ) )
print( sys.getsizeof( np.array(xVec_CONST, dtype = np.short)) )
print( sys.getsizeof( np.array(xVec_CONST, dtype = np.int)  ) )

100
112
64
64
80
112
